# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - '*'


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- script: |
    echo "Downloading Terraform..."
    wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
    unzip terraform_0.15.5_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform --version
  displayName: 'Install Terraform'

- checkout: self

- script: |
    terraform init -migrate-state
    terraform plan -out=tfplan
  displayName: 'Terraform Init and Plan'

- script: |
    terraform apply -auto-approve tfplan
    cp terraform.tfstate $(Agent.TempDirectory)/terraform.tfstate

  displayName: 'Terraform Apply'

- task: PublishBuildArtifacts@1  
  inputs:
      pathtoPublish: '$(Agent.TempDirectory)/terraform.tfstate'
      artifactName: 'terraform-state'
      publishLocation: 'container'
  displayName: 'Publish Terraform State'
